BookStore/Areas/Admin/Controllers/CoverTypeController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Utility;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CoverTypeController : Controller
    {
        private ApplicationDbContext _db;

        public CoverTypeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var objCoverTypeList = _db.CoverTypes.ToList();
            return View(objCoverTypeList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {

            if (ModelState.IsValid)
            {
                _db.CoverTypes.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Cover Type created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }



        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var coverTypeFromDb = _db.CoverTypes.Find(id);

            if (coverTypeFromDb == null)
            {
                return NotFound();
            }

            return View(coverTypeFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {

            if (ModelState.IsValid)
            {
                _db.CoverTypes.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Cover Type updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var coverTypeFromDb = _db.CoverTypes.Find(id);

            if (coverTypeFromDb == null)
            {
                return NotFound();
            }

            return View(coverTypeFromDb);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.CoverTypes.Find(id);

            if (obj == null)
            {
                return NotFound();
            }

            _db.CoverTypes.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Cover Type deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

BookStore/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
	<div class="border p-3 mt-4">
		<div class="pb-2">
			<h2 class="text-primary">Create Cover Type</h2>
			<hr />
		</div>		

		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>		
		<button type="submit" class="btn btn-primary"
				style="width:150px">
			Create
		</button>
		<a asp-controller="CoverType" asp-action="Index"
		   class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BookStore/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType
<form method="post" asp-action="Delete">
	<input type="hidden" asp-for="Id">
	<div class="border p-3 mt-4">
		<div class="pb-2">
			<h2 class="text-primary">Delete Cover Type</h2>
			<hr />
		</div>
	

		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
			
		</div>		
		<button type="submit" class="btn btn-primary"
				style="width:150px">
			Delete
		</button>
		<a asp-controller="Category" asp-action="Index" 
			class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial"/>
	}
}

BookStore/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post">
	<div class="border p-3 mt-4">
		<div class="pb-2">
			<h2 class="text-primary">Edit Cover Type</h2>
			<hr />
		</div>		

		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>		
		<button type="submit" class="btn btn-primary"
				style="width:150px">
			Update
		</button>
		<a asp-controller="CoverType" asp-action="Index"
		   class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BookStore/Areas/Admin/Views/CoverType/Index.cshtml
@model List<CoverType>

<div class="container p-3">
	<div class="row pt-4">
		<div class="col-6">
			<h2 class="text-primary">Cover Types List</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="CoverType" asp-action="Create" class="btn btn-primary">
				<i class="bi bi-plus-circle"></i>&nbsp; Create New Cover Type
			</a>
		</div>
	</div>
</div>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th> Cover Type</th>			
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var obj in Model)
		{
			<tr>
				<td>
					@obj.Name
				</td>				
				<td>
					<div class="w-75 btn-group">
						<a asp-controller="CoverType"
						   asp-action="Edit"
						   asp-route-id="@obj.Id"
						   class="btn btn-primary">
							<i class="bi bi-pencil-square mx-2"></i>
							Edit
						</a>
						<a asp-controller="CoverType"
						   asp-action="Delete"
						   asp-route-id="@obj.Id"
						   class="btn btn-danger mx-2">
							<i class="bi bi-trash-fill"></i>
							Delete
						</a>

					</div>
				</td>
			</tr>
		}
	</tbody>
</table>